import 'dart:convert';

import 'package:shared_preferences/shared_preferences.dart';

import '../../models/user_model.dart';

/// The notification types a person can switch on and off, one row each in
/// Settings > "Choose what you get" — the same keys, labels and groups the
/// web dashboard lists (server/utils/notificationTypes.js is the canonical
/// catalog), and the same keys the per-topic push mirror below and every
/// local banner path look up. Kept here, a plain-Dart file with no Flutter
/// imports, so the background isolates can use the keys too.
abstract final class NotificationTypes {
  static const auditCreated = 'audit_created';
  static const auditSeriesCreated = 'audit_series_created';
  static const auditReassigned = 'audit_reassigned';
  static const auditSkipped = 'audit_skipped';
  static const auditCompleted = 'audit_completed';
  static const auditOverdue = 'audit_overdue';
  // Push-only: generated by this phone's own poll, never by the server, so
  // there is no email for it.
  static const auditReminder = 'audit_reminder';
  static const ncRaised = 'nc_raised';
  static const ncResponded = 'nc_responded';
  static const ncApproved = 'nc_approved';
  static const ncRejected = 'nc_rejected';
  static const ncOverdue = 'nc_overdue';
  static const morningSummary = 'morning_summary';
  static const eveningSummary = 'evening_summary';
  static const ticketCreated = 'ticket_created';
  static const ticketReply = 'ticket_reply';
  static const ticketStatus = 'ticket_status';
  static const ticketForwarded = 'ticket_forwarded';
}

class NotificationTopic {
  final String key;
  final String group;
  final String label;
  final String description;
  // False only for a topic that has no email at all (audit_reminder).
  final bool emailApplies;

  const NotificationTopic(
    this.key,
    this.group,
    this.label,
    this.description, {
    this.emailApplies = true,
  });
}

const kNotificationGroupAudits = 'Audits';
const kNotificationGroupNcs = 'Non-conformances (NC)';
const kNotificationGroupSummaries = 'Daily summaries';
const kNotificationGroupTickets = 'Support tickets';

/// Display order of the groups.
const kNotificationGroups = [
  kNotificationGroupAudits,
  kNotificationGroupNcs,
  kNotificationGroupSummaries,
  kNotificationGroupTickets,
];

/// Every switchable topic, in display order within its group.
const kNotificationTopics = [
  NotificationTopic(
    NotificationTypes.auditCreated,
    kNotificationGroupAudits,
    'New audit assigned',
    'When an audit is scheduled and you are its auditor or auditee.',
  ),
  NotificationTopic(
    NotificationTypes.auditSeriesCreated,
    kNotificationGroupAudits,
    'Recurring audit series created',
    'When a repeating audit series is set up and you are part of it.',
  ),
  NotificationTopic(
    NotificationTypes.auditReassigned,
    kNotificationGroupAudits,
    'Audit reassigned',
    'When an audit is assigned to you, or you are removed from one.',
  ),
  NotificationTopic(
    NotificationTypes.auditSkipped,
    kNotificationGroupAudits,
    'Audit skipped',
    'When an audit you are on is skipped, or a skipped audit is put back on the schedule.',
  ),
  NotificationTopic(
    NotificationTypes.auditCompleted,
    kNotificationGroupAudits,
    'Audit completed',
    'When an audit you are on is marked completed.',
  ),
  NotificationTopic(
    NotificationTypes.auditOverdue,
    kNotificationGroupAudits,
    'Audit due / overdue',
    'When an audit passes its due date and is still not completed.',
  ),
  NotificationTopic(
    NotificationTypes.auditReminder,
    kNotificationGroupAudits,
    'Audit start and due-date reminders',
    'Reminders that your phone shows before an audit starts and before it is due.',
    emailApplies: false,
  ),
  NotificationTopic(
    NotificationTypes.ncRaised,
    kNotificationGroupNcs,
    'NC raised',
    'When a non-conformance is raised against you.',
  ),
  NotificationTopic(
    NotificationTypes.ncResponded,
    kNotificationGroupNcs,
    'NC response submitted',
    'When the auditee sends a response to an NC you raised, ready for your review.',
  ),
  NotificationTopic(
    NotificationTypes.ncApproved,
    kNotificationGroupNcs,
    'NC response approved',
    'When your response to an NC is accepted and the NC is closed.',
  ),
  NotificationTopic(
    NotificationTypes.ncRejected,
    kNotificationGroupNcs,
    'NC response rejected',
    'When your response to an NC is rejected and you need to rework it.',
  ),
  NotificationTopic(
    NotificationTypes.ncOverdue,
    kNotificationGroupNcs,
    'NC overdue',
    'When your response to an NC is past its target date.',
  ),
  NotificationTopic(
    NotificationTypes.morningSummary,
    kNotificationGroupSummaries,
    'Morning summary',
    'Your day at a glance: audits starting or due today, what is overdue and any new NC.',
  ),
  NotificationTopic(
    NotificationTypes.eveningSummary,
    kNotificationGroupSummaries,
    'Evening summary',
    'Your wrap-up: what was completed today and what is still overdue.',
  ),
  NotificationTopic(
    NotificationTypes.ticketCreated,
    kNotificationGroupTickets,
    'New support ticket',
    'When a new support ticket is raised for you to handle.',
  ),
  NotificationTopic(
    NotificationTypes.ticketReply,
    kNotificationGroupTickets,
    'Reply on a ticket',
    'When someone replies on a support ticket you are part of.',
  ),
  NotificationTopic(
    NotificationTypes.ticketStatus,
    kNotificationGroupTickets,
    'Ticket status / confirmation needed',
    'When a ticket moves forward, or when you need to confirm that it is fixed.',
  ),
  NotificationTopic(
    NotificationTypes.ticketForwarded,
    kNotificationGroupTickets,
    'Escalated to Developer',
    'When a support ticket is escalated to the Developer.',
  ),
];

/// One consistent reading of "may a push be shown right now" for code that
/// makes several decisions in one go (a poll tick): the account's master
/// Push switch and the per-topic values, read once. A topic missing from
/// [types] — or one that is not in the catalog at all — is governed by the
/// master alone.
class PushGate {
  final bool enabled;
  final Map<String, bool> types;

  const PushGate({required this.enabled, this.types = const {}});

  bool allows(String type) => enabled && (types[type] ?? true);
}

/// Plain, isolate-safe key/value access for everything the background poll
/// needs — no Provider/Riverpod/DI container reaches into a background
/// isolate (AndroidAlarmManager callbacks and the background_service
/// isolate both start with a bare Dart VM, nothing else registered), so
/// this is deliberately the ONLY way state crosses between the foreground
/// app and the background pipeline. SharedPreferences (not
/// flutter_secure_storage) on purpose: it's a plain-old platform channel
/// with no keychain/keystore session to re-establish, so it's the one
/// storage mechanism guaranteed to behave identically in a background
/// isolate with no prior Flutter engine warm-up.
///
/// AuthProvider mirrors the token here on login/logout (see
/// notification_scheduler.dart#onAuthChanged) — flutter_secure_storage
/// stays the source of truth for the foreground app, this is just a
/// same-value copy the background isolate can actually reach.
class NotificationPrefs {
  NotificationPrefs._();

  static const _tokenKey = 'bg_auth_token';
  static const _userIdKey = 'bg_user_id';
  static const _notifiedIdsKey = 'bg_notified_nc_ids';

  // ── Session-scoped dedup state for the event poll (event_poll.dart) ──
  // Same idea as _notifiedIdsKey above, one bucket per event type so one
  // type's bookkeeping never resurrects stale state from another.
  // Cleared only on an ACCOUNT CHANGE (see [setSession]), not on
  // every logout — a different account logging in on this device
  // shouldn't inherit "already seen" state that was never about them, but
  // the SAME person re-authenticating (a forced logout on token expiry is
  // common, not just an explicit Sign Out) should still see every
  // already-acknowledged reminder stay acknowledged, not re-fire as if it
  // were brand new.
  static const _seenAuditIdsKey = 'bg_seen_audit_ids';
  static const _auditBaselineSeededKey = 'bg_audit_baseline_seeded';
  static const _notifiedAuditDatesKey = 'bg_notified_audit_dates';
  static const _seenNcIdsKey = 'bg_seen_new_nc_ids';
  static const _ncBaselineSeededKey = 'bg_nc_baseline_seeded';
  static const _ncLastStatusKey = 'bg_nc_last_status';

  // ── Push switch mirror ────────────────────────────────────────────────
  // The account's preferences.pushNotifications — the single server-side
  // switch the web Settings page shares — copied here because everything
  // that decides whether to SHOW something has no way to reach
  // AuthProvider: the two background poll isolates, the FCM background
  // handler, the socket-driven banner. AuthProvider writes it on login,
  // app resume, a 'preferences_updated' socket event and the Settings
  // switch; every poll tick also refreshes it from the server itself (see
  // event_poll.dart#refreshPushGate), which is the only way the killed-
  // app foreground service can hear about a change made on the web.
  //
  // Defaults ON, same as the server treats a missing value. Deliberately
  // left out of clearSession() below: nothing polls or receives a push
  // while logged out, and the next login rewrites it before anything
  // reads it.
  static const _pushEnabledKey = 'notif_push_enabled';

  static Future<bool> readPushEnabled() async {
    final prefs = await SharedPreferences.getInstance();
    // Each isolate keeps its own in-memory copy of SharedPreferences from
    // its first getInstance() and never sees another isolate's later
    // writes on its own — without this a background isolate would keep
    // obeying the value it started with after the Settings switch flipped.
    await prefs.reload();
    return prefs.getBool(_pushEnabledKey) ?? true;
  }

  static Future<void> setPushEnabled(bool value) async {
    final prefs = await SharedPreferences.getInstance();
    await prefs.setBool(_pushEnabledKey, value);
  }

  // ── Per-topic push mirror ─────────────────────────────────────────────
  // preferences.pushNotificationTypes — the account's EFFECTIVE per-topic
  // push values (the server already folded its legacy fallback in) — as a
  // JSON object, for the same isolate-safety reason as the master mirror
  // above and refreshed at exactly the same moments. Unlike the master it
  // IS wiped on logout ([clearSession]): a topic opted out under one
  // account must never silence a different account signing in on this
  // phone. An empty mirror reads as "every topic on", so the worst it can do
  // in the instant before the next login rewrites it is let the master
  // switch alone decide — it can never hide something the account wants.
  static const _pushTypesKey = 'notif_push_types';

  /// Every topic's mirrored push value; a topic that isn't in the map is on.
  static Future<Map<String, bool>> readPushTypes() async {
    final prefs = await SharedPreferences.getInstance();
    // Same cross-isolate staleness as readPushEnabled above.
    await prefs.reload();
    final raw = prefs.getString(_pushTypesKey);
    if (raw == null || raw.isEmpty) return const {};
    try {
      return UserPreferences.parseTypeMap(jsonDecode(raw));
    } catch (_) {
      return const {};
    }
  }

  static Future<bool> readPushTypeEnabled(String type) async =>
      (await readPushTypes())[type] ?? true;

  static Future<void> setPushTypes(Map<String, bool> types) async {
    final prefs = await SharedPreferences.getInstance();
    await prefs.setString(_pushTypesKey, jsonEncode(types));
  }

  /// The master switch and the per-topic values as one snapshot.
  static Future<PushGate> readPushGate() async =>
      PushGate(enabled: await readPushEnabled(), types: await readPushTypes());

  /// Whether a push of [type] may be SHOWN on this phone: the account's
  /// master Push switch AND that topic's own push switch. What the socket
  /// banner and the FCM renderers ask before drawing anything.
  static Future<bool> readPushAllowed(String type) async =>
      await readPushEnabled() && await readPushTypeEnabled(type);

  // ── Retired phone-local switches (one-time migration) ─────────────────
  // Settings used to carry a phone-only "Notifications" master switch and
  // six per-type reminder toggles, none of which the server ever saw. They
  // were replaced by the account-level push switch above. The master
  // switch was an explicit opt-out worth honouring once: a device that had
  // it OFF carries that over as push OFF on the account (AuthProvider does
  // the server write, then calls [finishLegacyMigration]). Everything else
  // is simply dropped.
  static const _legacyMigratedKey = 'notif_prefs_migrated_v1';
  static const _legacyBgPollingKey = 'notif_bg_polling_enabled';
  static const _legacyKeys = [
    _legacyBgPollingKey,
    'notif_audit_assigned',
    'notif_audit_start',
    'notif_audit_end',
    'notif_nc_raised',
    'notif_nc_approved',
    'notif_nc_rejected',
  ];

  /// True while this device still holds an explicit "Notifications: off"
  /// that hasn't been carried over to the account yet. The old switch
  /// defaulted ON, so only a stored `false` counts as a choice.
  static Future<bool> readLegacyPushOptOut() async {
    final prefs = await SharedPreferences.getInstance();
    if (prefs.getBool(_legacyMigratedKey) ?? false) return false;
    return prefs.getBool(_legacyBgPollingKey) == false;
  }

  /// Drops every retired key and marks the migration done so it never
  /// runs (or re-reads a stale opt-out) again.
  static Future<void> finishLegacyMigration() async {
    final prefs = await SharedPreferences.getInstance();
    for (final key in _legacyKeys) {
      await prefs.remove(key);
    }
    await prefs.setBool(_legacyMigratedKey, true);
  }

  /// Writes the new session — and, only when the account logging in is
  /// DIFFERENT from whoever was last signed in on this device, wipes every
  /// dedup set above first. Comparing against the OUTGOING userId (still
  /// on disk here since [clearSession] deliberately leaves it) is what
  /// lets a same-person re-login be told apart from an actual account
  /// switch; a first-ever login on this device (previousUserId null) has
  /// no dedup state to wipe either way.
  static Future<void> setSession({required String token, required String userId}) async {
    final prefs = await SharedPreferences.getInstance();
    final previousUserId = prefs.getString(_userIdKey);
    if (previousUserId != null && previousUserId != userId) {
      await prefs.remove(_notifiedIdsKey);
      await prefs.remove(_seenAuditIdsKey);
      await prefs.remove(_auditBaselineSeededKey);
      await prefs.remove(_notifiedAuditDatesKey);
      await prefs.remove(_seenNcIdsKey);
      await prefs.remove(_ncBaselineSeededKey);
      await prefs.remove(_ncLastStatusKey);
    }
    await prefs.setString(_tokenKey, token);
    await prefs.setString(_userIdKey, userId);
  }

  /// Called on logout. Clears the token — a stopped background poll has
  /// nothing to authenticate with either way (see
  /// background_entrypoints.dart#stopBackgroundPolling) — and the per-topic
  /// push mirror (see above), and leaves userId and every dedup set above
  /// untouched, so the NEXT [setSession]
  /// can tell whether it's the same person logging back in (keep the
  /// dedup state) or a different account on this shared device (wipe it).
  static Future<void> clearSession() async {
    final prefs = await SharedPreferences.getInstance();
    await prefs.remove(_tokenKey);
    await prefs.remove(_pushTypesKey);
  }

  static Future<String?> readToken() async => (await SharedPreferences.getInstance()).getString(_tokenKey);

  static Future<String?> readUserId() async => (await SharedPreferences.getInstance()).getString(_userIdKey);

  /// NC ids already surfaced as a local notification — checked before
  /// showing one, so the foreground app's own socket-driven notification
  /// (NotificationsProvider) and this background poll never double-announce
  /// the same overdue NC to the user.
  static Future<Set<String>> readNotifiedIds() async {
    final prefs = await SharedPreferences.getInstance();
    return (prefs.getStringList(_notifiedIdsKey) ?? const []).toSet();
  }

  static Future<void> addNotifiedIds(Iterable<String> ids) async {
    final prefs = await SharedPreferences.getInstance();
    final current = (prefs.getStringList(_notifiedIdsKey) ?? const []).toSet();
    current.addAll(ids);
    // Cap growth — only the most recent 500 ids are worth remembering;
    // an NC that old has long since been closed or re-surfaced anyway.
    final capped = current.length > 500 ? current.skip(current.length - 500).toSet() : current;
    await prefs.setStringList(_notifiedIdsKey, capped.toList());
  }

  // ── Audit-assigned dedup (event_poll.dart) ────────────────────────────

  /// Audit ids already observed in `/audits/mine` — used to detect a
  /// newly-assigned audit (an id that shows up that wasn't here before).
  static Future<Set<String>> readSeenAuditIds() async {
    final prefs = await SharedPreferences.getInstance();
    return (prefs.getStringList(_seenAuditIdsKey) ?? const []).toSet();
  }

  static Future<void> addSeenAuditIds(Iterable<String> ids) async {
    final prefs = await SharedPreferences.getInstance();
    final current = (prefs.getStringList(_seenAuditIdsKey) ?? const []).toSet();
    current.addAll(ids);
    final capped = current.length > 500 ? current.skip(current.length - 500).toSet() : current;
    await prefs.setStringList(_seenAuditIdsKey, capped.toList());
  }

  /// True once one full poll has run for this session — gates the very
  /// first poll from announcing every already-assigned audit as "new".
  static Future<bool> readAuditBaselineSeeded() async {
    final prefs = await SharedPreferences.getInstance();
    return prefs.getBool(_auditBaselineSeededKey) ?? false;
  }

  static Future<void> setAuditBaselineSeeded() async {
    final prefs = await SharedPreferences.getInstance();
    await prefs.setBool(_auditBaselineSeededKey, true);
  }

  // ── Audit start/end date reminder dedup ───────────────────────────────

  /// Keys of the form "<auditId>:start" / "<auditId>:end" already fired —
  /// one entry per audit per boundary, so a reminder doesn't re-fire on
  /// every poll for the rest of the audit's scheduled window.
  static Future<Set<String>> readNotifiedAuditDates() async {
    final prefs = await SharedPreferences.getInstance();
    return (prefs.getStringList(_notifiedAuditDatesKey) ?? const []).toSet();
  }

  static Future<void> addNotifiedAuditDates(Iterable<String> keys) async {
    final prefs = await SharedPreferences.getInstance();
    final current = (prefs.getStringList(_notifiedAuditDatesKey) ?? const []).toSet();
    current.addAll(keys);
    final capped = current.length > 500 ? current.skip(current.length - 500).toSet() : current;
    await prefs.setStringList(_notifiedAuditDatesKey, capped.toList());
  }

  // ── New-NC-raised dedup ────────────────────────────────────────────────

  /// NC ids already observed in `/ncs/mine` — separate from
  /// `_notifiedIdsKey` above (that one tracks "already alerted overdue",
  /// a different question from "already seen at all").
  static Future<Set<String>> readSeenNcIds() async {
    final prefs = await SharedPreferences.getInstance();
    return (prefs.getStringList(_seenNcIdsKey) ?? const []).toSet();
  }

  static Future<void> addSeenNcIds(Iterable<String> ids) async {
    final prefs = await SharedPreferences.getInstance();
    final current = (prefs.getStringList(_seenNcIdsKey) ?? const []).toSet();
    current.addAll(ids);
    final capped = current.length > 500 ? current.skip(current.length - 500).toSet() : current;
    await prefs.setStringList(_seenNcIdsKey, capped.toList());
  }

  static Future<bool> readNcBaselineSeeded() async {
    final prefs = await SharedPreferences.getInstance();
    return prefs.getBool(_ncBaselineSeededKey) ?? false;
  }

  static Future<void> setNcBaselineSeeded() async {
    final prefs = await SharedPreferences.getInstance();
    await prefs.setBool(_ncBaselineSeededKey, true);
  }

  // ── NC approved/rejected transition dedup ─────────────────────────────

  /// Last-seen "status|reopenCount" per NC id — diffed each poll to catch
  /// a transition to Closed (approved) or a reopenCount bump (rejected)
  /// exactly once, the same way _notifiedIdsKey dedups the overdue alert.
  static Future<Map<String, String>> readNcLastStatus() async {
    final prefs = await SharedPreferences.getInstance();
    final raw = prefs.getString(_ncLastStatusKey);
    if (raw == null || raw.isEmpty) return {};
    try {
      return Map<String, String>.from(jsonDecode(raw) as Map);
    } catch (_) {
      return {};
    }
  }

  static Future<void> mergeNcLastStatus(Map<String, String> updates) async {
    if (updates.isEmpty) return;
    final prefs = await SharedPreferences.getInstance();
    final current = await readNcLastStatus();
    current.addAll(updates);
    // Same 500-entry cap spirit as the id sets above — trims oldest
    // (insertion-order) entries once it grows past what's worth keeping.
    final trimmed = current.length > 500
        ? Map<String, String>.fromEntries(current.entries.skip(current.length - 500))
        : current;
    await prefs.setString(_ncLastStatusKey, jsonEncode(trimmed));
  }
}
